use_frameworks!

target 'SwiftMaterialKeyboard_Example' do
  pod 'FontAwesomeKit'
  pod 'SwiftMaterialKeyboard', :path => '../'

  target 'SwiftMaterialKeyboard_Tests' do
    inherit! :search_paths

    
  end
end
